spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/covid?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dbsl3761

covid:
  api:
    url: http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson?_type=json&ServiceKey=
    serviceKey: UD1mSPQFRwq1xRkO8PMZFOCQWpKXiS09uxGA1pR7BI/nJj7/QcboB69jzxNpcVJkhilS3RdyOWtiA7yqAz1G4Q==

server:
  port: 7001
